---
Mysql_root_password: <Mysql_Root_Pass>
DB_USER: root
Mysql_Database: <Mysql_DB_Name>
Mysql_Username: <Mysql_DB_User>
Mysql_Password: <Mysql_DBUser_Pass>
Artifactory_Host: <Art_Host>
Mysql_Host: <Mysql_Host>
Artifactory_DNS: <Art_DNS>
nginx_cert_path: /etc/nginx/ssl/nginx.crt
nginx_key_path: /etc/nginx/ssl/nginx.key
